version: '3'

services:
  app:
    image: 'spring-boot-activemq'
    build:
      context: .
    container_name: spring-boot-activemq
    ports:
      - 8080:8080
    depends_on:
      - activemq
    environment:
      - ACTIVEMQ_URL=tcp://activemq:61616
      - ACTIVEMQ_USERNAME=admin
      - ACTIVEMQ_PASSWORD=admin
      - ACTIVEMQ_QUEUE=email_queue
    networks:
      - spring-boot-activemq-network

  activemq:
    image: 'rmohr/activemq:latest'
    ports:
      - 61616:61616
      - 8161:8161
    networks:
      - spring-boot-activemq-network

networks:
  spring-boot-activemq-network:
    driver: bridge